name: HuMInLabPlugin
version: '${project.version}'
main: org.huminlabs.huminlabplugin.HuMInLabPlugin
api-version: 1.19
depend: [ProtocolLib]
commands:
  getstage:
    description: Returns the stage of the player
    usage: /getstage
  setstage:
    description: Sets the stage of the player
    usage: /setstage <unit> <lessonID>
  nextstage:
    description: Goes to the next stage of the player
    usage: /nextstage
  prevstage:
    description: Goes to the previous stage of the player
    usage: /prevstage